Repair clean build
square/gradle-dependencies-sorter pull request #39
Opened 2023-03-08 08:17 UTC by jamesonwilliams

`./gradlew clean build` wasn't completing successfully, here's an example build scan:

  https://scans.gradle.com/s/bmeesvwv6djyk

Seems related to this Gradle issue with ANTLR:

  https://github.com/gradle/gradle/issues/19555

Adding a task dependency seems to resolve it. Here's a build scan showing the build after this commit:

  https://gradle.com/s/tgy2ddpjfjgxe

Resolves: https://github.com/square/gradle-dependencies-sorter/issues/38

2023-03-08 08:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/square/gradle-dependencies-sorter?pullRequest=39) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/square/gradle-dependencies-sorter?pullRequest=39) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/square/gradle-dependencies-sorter?pullRequest=39) it.</sub>

2023-03-12 06:13 UTC, ZacSweers requested changes

2023-03-12 06:13 UTC, ZacSweers commented on grammar/build.gradle
> +  tasks.findByPath(":grammar:sourcesJar").dependsOn(it)
This eagerly configures the task during the `generateGrammarSource` task's configuration. A better solution would be to do something like this outside this named block, which leverages lazy task configuration.

```kotlin
tasks.named(":grammar:sourcesJar") {
  dependsOn("generateGrammarSource")
}
```

2023-03-12 06:43 UTC, jamesonwilliams commented on grammar/build.gradle
> +  tasks.findByPath(":grammar:sourcesJar").dependsOn(it)
It seems to work when I pull it out of the `generateGrammarSource` block:
```diff
   ]
-  tasks.findByPath(":grammar:sourcesJar").dependsOn(it)
 }
+tasks.findByPath(":grammar:sourcesJar").dependsOn("generateGrammarSource")
```
However, using the `named` block isn't working:
```diff
   ]
-  tasks.findByPath(":grammar:sourcesJar").dependsOn(it)
+}
+tasks.named(":grammar:sourcesJar") {
+  dependsOn("generateGrammarSource")
 }
```
```console
$ ./gradlew clean build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jameson.williams/gradle-dependencies-sorter/grammar/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':grammar'.
> Task with name ':grammar:sourcesJar' not found in project ':grammar'.
[...snip...]
```
I can update to the first version? WDYT?

2023-03-12 06:51 UTC, ZacSweers commented on grammar/build.gradle
> +  tasks.findByPath(":grammar:sourcesJar").dependsOn(it)
First version has the same problem (findByPath is an eager API). Second one is the right solution sorry I should've just put "sourcesJar" and not the gradle project path with it. That should work?

2023-03-12 06:55 UTC, jamesonwilliams commented on grammar/build.gradle
> +  tasks.findByPath(":grammar:sourcesJar").dependsOn(it)
It works! https://github.com/square/gradle-dependencies-sorter/pull/39/commits/f88909b1d1ec4ecfd12ee7a171af4b72e37efa20

2023-03-12 07:07 UTC, ZacSweers commented on grammar/build.gradle
> +tasks.named("sourcesJar") {
Let's link the antlr issue for posterity

2023-03-12 07:25 UTC, jamesonwilliams commented on grammar/build.gradle
> +tasks.named("sourcesJar") {
Done in https://github.com/square/gradle-dependencies-sorter/pull/39/commits/ded65e9b377615fea8f7da6b9e932d39d30885c8

2023-03-14 19:56 UTC, ZacSweers approved these changes

2023-03-14 19:59 UTC, merged