Add strict mode to fail the Gradle task in case of parsing errors
square/gradle-dependencies-sorter pull request #67
Opened 2023-07-22 08:34 UTC by SimonMarquis

Closes #37

2023-07-22 22:28 UTC, jamesonwilliams approved these changes
LGTM

2023-07-22 22:28 UTC, jamesonwilliams commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +  @get:Option(option = "strict", description = "Enables strict mode.")
🔕  Trivial suggestion on documentation - 
```suggestion
  @get:Option(option = "strict", description = "Fails the task if the sort order cannot be verified/updated. A parse error could cause this. Default is true.")
```

2023-07-23 06:43 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +  @get:Option(option = "strict", description = "Enables strict mode.")
I feel like "strict mode" is universally understood in the case of such tools, and adding a non exhaustive list of examples is not necessary, but I'm ok to change it if @autonomousapps confirms.
Also, the current default value is `false`. Should we change it? (I'm for keeping it opt-in)

2023-07-24 05:06 UTC, autonomousapps requested changes
Thanks! Left some comments. While I'm not opposed to the user's potential desire to fail their build in the presence of parse errors, I don't think that is the correct default. Independently, I wouldn't make a behavior change like that outside of a major version change (but as I said, I'm also philosophically opposed to it).

In addition, could you add an entry to the **README** for this?

2023-07-24 05:06 UTC, autonomousapps commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +    val strict = strict.getOrElse(true)
default should be `false`

2023-07-24 05:06 UTC, autonomousapps commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +  @get:Option(option = "strict", description = "Enables strict mode.")
Default should be false. Description should be
```kotlin
"Enables strict mode, which will cause this task to fail if there is an error parsing or sorting the dependencies. Default is false."
```

2023-07-24 05:06 UTC, autonomousapps commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'sortDependencies', '--verbose')
Since the default will be false, you should pass the new option here in this test.

2023-07-24 07:39 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +    val strict = strict.getOrElse(true)
Oups, I completely forgot to flip this back to false (it was a test).

2023-07-24 07:57 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'sortDependencies', '--verbose')
The `strict` option is not part of the CLI, but only the `SortDependenciesTask`.
CLI will already return an exit code based on the parsing/sorting.
But now that I'm retring to tests these behaviors, it seems like `ExecOperations.javaexec` already throws and fails the task when there is a non-0 exit code, and therefore the root issue of #37 is something else.

2023-07-24 08:08 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'sortDependencies', '--verbose')
We need to configure the `JavaExecSpec` with `isIgnoreExitValue = true` to be able to manually handle non-0 exit code.
This means, tasks are already failing in the cases of `NO_PATH_PASSED`, `NO_BUILD_SCRIPTS_FOUND`, `NOT_SORTED`, `UNKNOWN_MODE`, `PARSE_ERROR`.
This also means adding this `strict` mode will change the current behavior.
Should I still proceed with these changes?

2023-07-24 18:23 UTC, autonomousapps reviewed
Something is not quite adding up 😅

2023-07-24 18:23 UTC, autonomousapps commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +    val strict = strict.getOrElse(false)
Should it be `getOrElse()` or `isPresent()`? Your docs suggest just passing `--strict` is all that is needed. If you want to _get_ the value, then users would pass `--strict=true` or `--strict=false` (I think).

2023-07-24 18:23 UTC, autonomousapps commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'checkSortDependencies', '--verbose', '--strict')
Why is this test changing?

2023-07-24 18:26 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +    val strict = strict.getOrElse(false)
I'm pretty sure Gradle do that by default for Boolean properties, but let me double check. (I followed what was done for the verbose parameter)

2023-07-24 18:27 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'checkSortDependencies', '--verbose', '--strict')
This test is changing because it is expected to fail: `buildAndFail`.

2023-07-24 18:36 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
> +    val strict = strict.getOrElse(false)
Confirmed.

> Describes an option with the value true or false. Passing the option on the command line treats the value as true, for example --foo equates to true. The absence of the option uses the default value of the property. For each boolean option, an opposite option is created automatically. For example, --no-foo is created for the provided option --foo and --bar is created for --no-bar. Options whose name starts with --no are disable options and set the option value to false. An opposite option is only created if no option with the same name already exists for the task.

https://docs.gradle.org/8.2/userguide/custom_tasks.html#sec:supported_task_option_data_types

2023-07-24 18:39 UTC, SimonMarquis commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'checkSortDependencies', '--verbose', '--strict')
And the current exit code for this test is `NOT_SORTED(3)`.
We must either:
- use the `--strict`
- or replace `buildAndFail` with `build`
- (or both)

2023-07-25 17:09 UTC, autonomousapps commented on sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
> +    def result = buildAndFail(dir, 'checkSortDependencies', '--verbose', '--strict')
The fact that you had to change the test suggests the default behavior has changed, and I don't want the default behavior to change. New behavior behind a flag is fine, but I don't want to change current behavior.

2023-07-25 18:15 UTC, SimonMarquis commented
Let's recap and make sure we are on the same page.
The current state of the main branch is:
If CLI returns non-zero exit code, the task fails (as I would expect).

This means any parsing error `PARSE_ERROR(5)` will fail the task, hence the use of `buildAndFail` in tests.

Therefore, if we want to configure this through a `strict` flag, we should instead have `true` as default value (and reflect the current behavior), and let users specify `--no-strict` (or `--strict=false`) to disable the default behavior.

That being said, if we go back to the main issue that lead to this PR, the output was the following:

```
Metrics:
  Not sorted:     0
  Already sorted: 1
  Parse errors:   1

...

BUILD SUCCESSFUL in 857ms
```

And here is the root issue! **This should have been reported as a parsing error and the build should have failed**.
Otherwise `check` mode would ignore parsing errors, while `sort` mode won't. And this makes not a lot of sense. Do you agree with that?

To be more precise, the root issue comes from this difference in behavior:

- in `sort` mode:

  ```kotlin
  private fun sort(/*...*/): Status {
    /*...*/
    return if (parseErrorCount == 0) SUCCESS else PARSE_ERROR
  }
  ```

- in `check` mode:

  ```kotlin
  private fun check(/*...*/): Status {
    /*...*/
    val success = notSorted.isEmpty() /* 🐛 This looks like an error to me! */
    /*...*/
    return if (success) {
      SUCCESS
    } else if (parseErrorCount > 0) {
      PARSE_ERROR
    } else {
      NOT_SORTED
    }
  }
  ```

---

What I propose is:
- fixing the root issue, which is `check` mode not failing as it should in case of parsing error
- (optional, if needed) offer an "ignore parsing error" flag instead.

2024-01-27 17:50 UTC, closed without merging